import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/homepagev1">HomepageV1</Link>
        </li>
        <li>
          <Link to="/homepagev2">HomepageV2</Link>
        </li>
        <li>
          <Link to="/checkout">Checkout</Link>
        </li>
        <li>
          <Link to="/contact">Contact</Link>
        </li>
        <li>
          <Link to="/blogdetail">BlogDetail</Link>
        </li>
        <li>
          <Link to="/page">Page</Link>
        </li>
        <li>
          <Link to="/booktable">BookTable</Link>
        </li>
        <li>
          <Link to="/contactus">ContactUs</Link>
        </li>
        <li>
          <Link to="/checkout1">Checkout1</Link>
        </li>
        <li>
          <Link to="/page1">Page1</Link>
        </li>
        <li>
          <Link to="/checkout2">Checkout2</Link>
        </li>
        <li>
          <Link to="/contactpage">ContactPage</Link>
        </li>
        <li>
          <Link to="/vaccineinformation">VaccineInformation</Link>
        </li>
        <li>
          <Link to="/faq">FAQ</Link>
        </li>
        <li>
          <Link to="/contact1">Contact1</Link>
        </li>
        <li>
          <Link to="/ticket">Ticket</Link>
        </li>
        <li>
          <Link to="/blogdetail1">BlogDetail1</Link>
        </li>
        <li>
          <Link to="/herosection">HeroSection</Link>
        </li>
        <li>
          <Link to="/shoppingcart">ShoppingCart</Link>
        </li>
        <li>
          <Link to="/contactus1">ContactUs1</Link>
        </li>
        <li>
          <Link to="/homestyle">HomeStyle</Link>
        </li>
        <li>
          <Link to="/personalblogpostwithsidebar2">
            PersonalBlogPostwithsidebar2
          </Link>
        </li>
        <li>
          <Link to="/contactus2">ContactUs2</Link>
        </li>
        <li>
          <Link to="/checkout3">Checkout3</Link>
        </li>
        <li>
          <Link to="/cart">Cart</Link>
        </li>
        <li>
          <Link to="/templatecategory2">TemplateCategory2</Link>
        </li>
        <li>
          <Link to="/contactus3">ContactUs3</Link>
        </li>
        <li>
          <Link to="/reservation">Reservation</Link>
        </li>
        <li>
          <Link to="/personalblogpostwithsidebar3">
            PersonalBlogPostwithsidebar3
          </Link>
        </li>
        <li>
          <Link to="/checkout4">Checkout4</Link>
        </li>
        <li>
          <Link to="/cart1">Cart1</Link>
        </li>
        <li>
          <Link to="/contactus4">ContactUs4</Link>
        </li>
        <li>
          <Link to="/reservation1">Reservation1</Link>
        </li>
        <li>
          <Link to="/contactus5">ContactUs5</Link>
        </li>
        <li>
          <Link to="/blogdetail2">BlogDetail2</Link>
        </li>
        <li>
          <Link to="/home1">Home1</Link>
        </li>
        <li>
          <Link to="/blogdetail3">BlogDetail3</Link>
        </li>
        <li>
          <Link to="/medical002">Medical002</Link>
        </li>
        <li>
          <Link to="/ecommerce">Ecommerce</Link>
        </li>
        <li>
          <Link to="/ecommerce002">ECommerce002</Link>
        </li>
        <li>
          <Link to="/blogalt1">Blogalt1</Link>
        </li>
        <li>
          <Link to="/travel">Travel</Link>
        </li>
        <li>
          <Link to="/travel1">Travel1</Link>
        </li>
        <li>
          <Link to="/realestate">RealEstate</Link>
        </li>
        <li>
          <Link to="/beauty">Beauty</Link>
        </li>
        <li>
          <Link to="/donation">Donation</Link>
        </li>
        <li>
          <Link to="/restaurant002">Restaurant002</Link>
        </li>
        <li>
          <Link to="/restaurant001">Restaurant001</Link>
        </li>
        <li>
          <Link to="/landingpage">LandingPage</Link>
        </li>
        <li>
          <Link to="/business002">Business002</Link>
        </li>
        <li>
          <Link to="/heroimage">HeroImage</Link>
        </li>
        <li>
          <Link to="/contact2">Contact2</Link>
        </li>
        <li>
          <Link to="/contact3">Contact3</Link>
        </li>
        <li>
          <Link to="/page2">Page2</Link>
        </li>
        <li>
          <Link to="/page3">Page3</Link>
        </li>
        <li>
          <Link to="/page4">Page4</Link>
        </li>
        <li>
          <Link to="/page5">Page5</Link>
        </li>
        <li>
          <Link to="/page6">Page6</Link>
        </li>
        <li>
          <Link to="/home2">Home2</Link>
        </li>
        <li>
          <Link to="/carreservation">CarReservation</Link>
        </li>
        <li>
          <Link to="/contactsimple">ContactSimple</Link>
        </li>
        <li>
          <Link to="/loginregister">LoginRegister</Link>
        </li>
        <li>
          <Link to="/contactus6">ContactUs6</Link>
        </li>
        <li>
          <Link to="/digtalagency">DigtalAgency</Link>
        </li>
        <li>
          <Link to="/screen">Screen</Link>
        </li>
        <li>
          <Link to="/desktophd">DesktopHD</Link>
        </li>
        <li>
          <Link to="/home3">Home3</Link>
        </li>
        <li>
          <Link to="/blogdetail4">BlogDetail4</Link>
        </li>
        <li>
          <Link to="/blogdetail5">BlogDetail5</Link>
        </li>
        <li>
          <Link to="/blogdetail6">BlogDetail6</Link>
        </li>
        <li>
          <Link to="/blogdetail7">BlogDetail7</Link>
        </li>
        <li>
          <Link to="/artboard">Artboard</Link>
        </li>
        <li>
          <Link to="/artboard1">Artboard1</Link>
        </li>
        <li>
          <Link to="/artboard2">Artboard2</Link>
        </li>
        <li>
          <Link to="/artboard3">Artboard3</Link>
        </li>
        <li>
          <Link to="/invoicedetailweb">InvoiceDetailWeb</Link>
        </li>
        <li>
          <Link to="/landingpage1">LandingPage1</Link>
        </li>
        <li>
          <Link to="/propertypage">PropertyPage</Link>
        </li>
        <li>
          <Link to="/propertydetail">PropertyDetail</Link>
        </li>
        <li>
          <Link to="/orderlist">OrderList</Link>
        </li>
        <li>
          <Link to="/propertydetail1">PropertyDetail1</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
